# https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
build:
  stage: build
  # Debug version, because we need a shell apparently:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - $CI_PROJECT_DIR/gitlab-ci.sh
  only:
    - tags
