#
# kubectl apply -k .
#
# See Zabbix [1] and Docker Hub [2].
#
# [1] https://www.zabbix.com/container_images
# [2] https://hub.docker.com/r/zabbix/zabbix-server-mysql
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: zabbix-server
  template:
    metadata:
      labels:
        component: zabbix-server
    spec:
      containers:
        # docker run --name some-zabbix-server-mysql -e
        # DB_SERVER_HOST="some-mysql-server" -e MYSQL_USER="some-user"
        # -e MYSQL_PASSWORD="some-password" -d
        # zabbix/zabbix-server-mysql:tag
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql:centos-5.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10050
        env:
        - name: "DB_SERVER_HOST"
          value: "zabbix-db"
        - name: "DB_SERVER_PORT"
          value: "3306"
          # MySQL Root is used to create the user & database:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "root"
        - name: "MYSQL_USER"
          value: "zabbix"
        - name: "MYSQL_PASSWORD"
          value: "zabbix"
        - name: "MYSQL_DATABASE"
          value: "zabbix"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: zabbix-db
  template:
    metadata:
      labels:
        component: zabbix-db
    spec:
      containers:
        # docker run --name some-mysql -e
        # MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:tag
        #
        # With  v8.0  it my  happen  thata  the older  clients  cannot
        # connect  because of  the  changed default  by password  hash
        # algo.  Use  v5.7.  The CentOS based  zabbix server container
        # image brings an older mysqladmin and likely other tools.
        #
      - name: zabbix-db
        image: mysql:5.7.30
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "root"
          # Let the Zabbix Startup Procedure create the DB, avoid
          # collation issues:
        # - name: "MYSQL_USER"
        #   value: "zabbix"
        # - name: "MYSQL_PASSWORD"
        #   value: "zabbix"
        # - name: "MYSQL_DATABASE"
        #   value: "zabbix"
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-db
spec:
  type: ClusterIP
  selector:
    component: zabbix-db
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
spec:
  type: ClusterIP
  selector:
    component: zabbix-server
  ports:
  - port: 10050
    targetPort: 10050
...
